### ISSUE TITLE
base tzOffset set to 3600 

### ISSUE THREAD

**Issue by lcervo-diligent** [myvobot/dock-mini-apps#4]
I set the base city (using the designated application web page) to London and the OPTIONS.tzOffset value (or the return value of clocktime.tzoffset()) is now set to 3600. I changed it to Paris and that value is 7200. Shouldn't it be 0 for London and 3600 for Paris?

**Comment by pumpkin-zbh** [comment]
The timezone offsets you observed are correct because they reflect the current Daylight Saving Time (DST) status. Both London and Paris are currently in DST:

- London's timezone offset is 3600 seconds (BST).
- Paris's timezone offset is 7200 seconds (CEST).

If it were not DST, London should be 0 seconds (GMT) and Paris should be 3600 seconds (CET).

**Comment by lcervo-diligent** [comment]
yes!!! 🤦🏼
